### ISSUE TITLE
New Python Interface

### ISSUE THREAD

**Issue by harmsm** [braingram/pycmdmessenger#10]
Hi Brett,

I just put together a Python CmdMessenger interface that uses the binary string passing interface (https://github.com/harmsm/PyCmdMessenger).  It is quite robust at this point.   I switched to the binary strings interface after running into some of the same problems with user-readable strings you note on your page.  I thought you might want to know, in case you have any desire to revisit CmdMessenger in the future.  

Unfortunately, I named the project PyCmdMessenger without even checking for other packages of the same name (stupid of me; sorry about that!).  It's already up on pypi, so I'd rather not change the name.  If you've really abandoned your project--as it appears from your page--I would _love_ it if you could point a link to my project on your page before your warning.  I also hope you don't mind me using the PyCmdMessenger name.  

Thanks!

Mike

**Comment by braingram** [comment]
Sure thing!

Also, after washing my hands of cmdmessanger I wrote an alternative for the arduino and python called [Comando](https://github.com/braingram/comando). It's lacking complete documentation but I have been using it extensively in projects and have been quite happy with the ability to run multiple protocols and have working argument packing and unpacking.

Thanks,
Brett
